prometheus-node-exporter:
  enabled: false

kube-state-metrics:
  enabled: false

alertmanager:
  enabled: false

serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090

server:
  persistentVolume:
    enabled: false

  ingress:
    enabled: false

  resources:
    requests:
      cpu: 100m
      memory: 128Mi

    limits:
      cpu: 200m
      memory: 256Mi